version: '3.3'

services:
  mongodb:
    restart: unless-stopped
    image: mongo
    ports:
      - "27017:27017"

  api:
    container_name: cot-api
    build:
      context: src/api
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=prod
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "5000:5000"