version: '3.3'

services:
   db:
     container_name: mysql
     image: mysql:5.7
     volumes:
       - "~/data:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root


  api:
    container_name: cot-api
    build:
      context: src/api
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=debug
    depends_on:
      - db
    restart: always